---
title: "Getting set up with R, RStudio, and Git"
format: html
---

You first need to choose what computer to setup (you can do multiple if you would like)

- personal computer/laptop (recommened if possible)
- [CI Virtual Labs](http://go.csuci.edu/vdi) (recommended if you don't have a laptop you can configure software on) This allows you to use a web browser and it will look just like if you logged onto a school computer. When Microsoft asks for your email give it you school email, but instead of "@myci.csuci.edu" use "@csuci.edu".
- School computer (Only recommended if you plan to use the same class desktop for homework as well)

## Installing R and RStudio

1. Install [R](https://cran.rstudio.com/).
2. Install [RStudio](https://posit.co/download/rstudio-desktop/).

## Getting setup with Git

3. Make a [GitHub account](https://github.com/). If you already have one you can use it.
4. Check if you already have Git installed. Macs typically already have it installed. You can check by going to the **Terminal** in RStudio and typing `which git`. 

If it says it does not recognize the command, then you do not have Git installed. Installation differs by operating system, if you have:

- Windows (and CI Virtual Lab), use this link to install [Git](https://gitforwindows.org/).
- Mac, in the Terminal in RStudio enter `git --version`, then `git config`, then accept the offer and click "Install".
- For linux or any issues installing Git follow [this guide](https://happygitwithr.com/install-git#linux) specific to your operating system.

5. Introduce yourself to Git. To do this run each of the following lines of code in the **Console** in RStudio. Make sure to change "Jane Doe" to your GitHub username and "jane@example.org" to the email you used for your GitHub account.

```{r}
#| eval: false

install.packages("usethis")
library(usethis)
use_git_config(user.name = "Jane Doe", user.email = "jane@example.org")
```

## Connecting / Configuring GitHub with your RStudio

6. We need to generate an SSH key in RStudio and then provide it to GitHub. Follow the steps in the video below.

<center>

<video width="80%" height="45%" align = "center" controls>
  <source src="screencast/00d-ssh-setup.mp4" type="video/mp4">
</video>

</center>

7. You're all done!! 

